### PR TITLE
Calling json_decode with $assoc = true

### PR DESCRIPTION
**Pull request by ghost**
Changing call of json_decode in second parameter to return associative arrays.

When I tried to loop over json imports like [fritz.zip](https://github.com/Perlkonig/grav-plugin-import/files/2113858/fritz.zip) in twig template, it didn't work. After patching the code this way it was easy. I think it could generally be useful, since json_decode behaves now similar to Yaml::parse used for Yaml import.

Forgive me if it's nonsense, my php knowledge is not to deep.

### CODE REVIEW

**Comment by Perlkonig** [comment]
Thanks, but I don't understand the problem. What was it you couldn't do?

I'm not against the change, but I need to test for backwards compatibility first. It would help if I could see the code you tried that didn't work in the first place. Thanks!

**Comment by ghost** [comment]
I did code in twig `{% set glaserByPlz =  page.header.imports.mitglieder|sort_by_key('plz') %}` or something like
`{% for username, mitglied in page.header.imports.mitglieder %}`, that results on errors with `$assoc=false`, but works with `$assoc = true`. I could not call toArray from twig without error.

**Comment by Perlkonig** [comment]
Accepting and testing. Thanks!

**Comment by Perlkonig** [comment]
New release published.

**Comment by ghost** [comment]
Thank you!

**Pull request merged**
